import json

# 아티스트 리스트와 대표곡 슬러그 매핑 (아티스트당 약 7~10곡, 총 100명 = 약 800곡 이상 목표)
# '아티스트명': ('아티스트슬러그', ['곡슬러그1', '곡슬러그2', ...], '주활동연대')
DATA = {
    "Nirvana": ("nirvana", ["smells-like-teen-spirit", "come-as-you-are", "lithium", "heart-shaped-box", "in-bloom", "about-a-girl", "all-apologies", "pennyroyal-tea"], "90s"),
    "Radiohead": ("radiohead", ["creep", "fake-plastic-trees", "karma-police", "high-and-dry", "no-surprises", "paranoid-android", "exit-music", "let-down", "just"], "90s"),
    "Oasis": ("oasis", ["wonderwall", "dont-look-back-in-anger", "champagne-supernova", "live-forever", "supersonic", "stand-by-me", "some-might-say", "morning-glory"], "90s"),
    "Green Day": ("green-day", ["basket-case", "when-i-come-around", "good-riddance-time-of-your-life", "american-idiot", "boulevard-of-broken-dreams", "wake-me-up-when-september-ends", "holiday", "brain-stew"], "90s"),
    "Mariah Carey": ("mariah-carey", ["always-be-my-baby", "hero", "fantasy", "vision-of-love", "we-belong-together", "without-you", "obsessed", "all-i-want-for-christmas-is-you"], "90s"),
    "Pearl Jam": ("pearl-jam", ["black", "even-flow", "alive", "jeremy", "better-man", "yellow-ledbetter", "daughter", "corduroy"], "90s"),
    "Red Hot Chili Peppers": ("red-hot-chili-peppers", ["under-the-bridge", "californication", "scar-tissue", "otherside", "cant-stop", "dani-california", "by-the-way", "snow-hey-oh"], "90s"),
    "Madonna": ("madonna", ["vogue", "like-a-prayer", "ray-of-light", "frozen", "hung-up", "material-girl", "like-a-virgin", "la-isla-bonita"], "90s"),
    "Coldplay": ("coldplay", ["the-scientist", "yellow", "viva-la-vida", "clocks", "fix-you", "paradise", "magic", "a-sky-full-of-stars", "hymn-for-the-weekend"], "00s"),
    "Linkin Park": ("linkin-park", ["in-the-end", "numb", "what-ive-done", "crawling", "somewhere-i-belong", "breaking-the-habit", "faint", "bleed-it-out"], "00s"),
    "Maroon 5": ("maroon-5", ["she-will-be-loved", "sunday-morning", "this-love", "harder-to-breathe", "moves-like-jagger", "payphone", "sugar", "girls-like-you"], "00s"),
    "Beyonce": ("beyonce", ["crazy-in-love", "halo", "irreplaceable", "single-ladies", "if-i-were-a-boy", "love-on-top", "drunk-in-love", "formation"], "00s"),
    "Rihanna": ("rihanna", ["umbrella", "dont-stop-the-music", "take-a-bow", "disturbia", "diamonds", "we-found-love", "work", "stay", "only-girl"], "00s"),
    "Britney Spears": ("britney-spears", ["toxic", "baby-one-more-time", "oops-i-did-it-again", "womanizer", "gimme-more", "circus", "piece-of-me", "lucky"], "00s"),
    "Justin Timberlake": ("justin-timberlake", ["cry-me-a-river", "what-goes-around-comes-around", "rock-your-body", "sexyback", "my-love", "mirrors", "cant-stop-the-feeling", "suit-and-tie"], "00s"),
    "The Killers": ("the-killers", ["mr-brightside", "somebody-told-me", "when-you-were-young", "human", "read-my-mind", "all-these-things-that-ive-done", "smile-like-you-mean-it"], "00s"),
    "The Strokes": ("the-strokes", ["last-nite", "reptilia", "someday", "hard-to-explain", "you-only-live-once", "machu-picchu", "under-cover-of-darkness", "12-51"], "00s"),
    "Muse": ("muse", ["supermassive-black-hole", "starlight", "uprising", "time-is-running-out", "hysteria", "plug-in-baby", "knights-of-cydonia", "resistance"], "00s"),
    "John Mayer": ("john-mayer", ["gravity", "your-body-is-a-wonderland", "waiting-on-the-world-to-change", "slow-dancing-in-a-burning-room", "new-light", "free-fallin", "neon", "half-of-my-heart"], "00s"),
    "Taylor Swift": ("taylor-swift", ["love-story", "you-belong-with-me", "teardrops-on-my-guitar", "our-song", "blank-space", "shake-it-off", "anti-hero", "cruel-summer", "cardigan", "willow", "lover"], "10s"),
    "Katy Perry": ("katy-perry", ["i-kissed-a-girl", "hot-n-cold", "teenage-dream", "firework", "roaring", "dark-horse", "california-gurls", "last-friday-night"], "10s"),
    "Bruno Mars": ("bruno-mars", ["just-the-way-you-are", "talking-to-the-moon", "grenade", "locked-out-of-heaven", "when-i-was-your-man", "uptown-funk", "treasure", "thats-what-i-like"], "10s"),
    "Adele": ("adele", ["someone-like-you", "rolling-in-the-deep", "hello", "set-fire-to-the-rain", "make-you-feel-my-love", "when-we-were-young", "easy-on-me", "skyfall"], "10s"),
    "Ed Sheeran": ("ed-sheeran", ["thinking-out-loud", "perfect", "shape-of-you", "photograph", "castle-on-the-hill", "the-a-team", "galway-girl", "bad-habits"], "10s"),
    "Justin Bieber": ("justin-bieber", ["love-yourself", "sorry", "what-do-you-mean", "baby", "peaches", "intentions", "yummy", "boyfriend"], "10s"),
    "Ariana Grande": ("ariana-grande", ["thank-u-next", "no-tears-left-to-cry", "into-you", "7-rings", "positions", "we-cant-be-friends", "yes-and", "dangerous-woman"], "10s"),
    "The Weeknd": ("the-weeknd", ["blinding-lights", "starboy", "the-hills", "cant-feel-my-face", "save-your-tears", "die-for-you", "out-of-time", "is-there-someone-else"], "10s"),
    "Imagine Dragons": ("imagine-dragons", ["radioactive", "demons", "believer", "thunder", "whatever-it-takes", "natural", "bones", "enemy"], "10s"),
    "Twenty One Pilots": ("twenty-one-pilots", ["stressed-out", "ride", "heathens", "chlorine", "tear-in-my-heart", "car-radio", "heavydirtysoul", "shy-away"], "10s"),
    "Billie Eilish": ("billie-eilish", ["bad-guy", "ocean-eyes", "when-the-partys-over", "happier-than-ever", "what-was-i-made-for", "everything-i-wanted", "bury-a-friend", "lovely"], "20s"),
    "Shawn Mendes": ("shawn-mendes", ["stitches", "treat-you-better", "theres-nothing-holdin-me-back", "in-my-blood", "senorita", "mercy", "lost-in-japan", "wonder"], "10s"),
    "Dua Lipa": ("dua-lipa", ["new-rules", "dont-start-now", "idgaf", "levitating", "dance-the-night", "houdini", "physical", "one-kiss"], "20s"),
    "Lana Del Rey": ("lana-del-rey", ["summertime-sadness", "young-and-beautiful", "video-games", "born-to-die", "west-coast", "blue-jeans", "national-anthem", "cinnamon-girl"], "10s"),
    "Post Malone": ("post-malone", ["circles", "rockstar", "better-now", "sunflower", "congratulations", "white-iverson", "goodbyes", "chemical"], "10s"),
    "Arctic Monkeys": ("arctic-monkeys", ["do-i-wanna-know", "r-u-mine", "505", "fluorescent-adolescent", "mardy-bum", "i-bet-you-look-good-on-the-dancefloor", "arabella", "why-d-you-only-call-me-when-youre-high"], "10s"),
    "Olivia Rodrigo": ("olivia-rodrigo", ["drivers-license", "good-4-u", "deja-vu", "traitor", "vampire", "brutal", "happier", "favorite-crime", "get-him-back"], "20s"),
    "Harry Styles": ("harry-styles", ["as-it-was", "watermelon-sugar", "falling", "golden", "late-night-talking", "sign-of-the-times", "adore-you", "matilda"], "20s"),
    "SZA": ("sza", ["kill-bill", "good-days", "snooze", "the-weekend", "broken-clocks", "supermodel", "love-galore", "normal-girl"], "20s"),
    "Chappell Roan": ("chappell-roan", ["good-luck-babe", "pink-pony-club", "red-wine-supernova", "hot-to-go", "casual", "my-kink-is-karma", "femininomenon"], "20s"),
    "NewJeans": ("newjeans", ["hype-boy", "super-shy", "ditto", "omg", "attention", "cookie", "eta", "cool-with-you"], "20s"),
    "Lady Gaga": ("lady-gaga", ["bad-romance", "just-dance", "poker-face", "paparazzi", "born-this-way", "shallow", "telephone", "alejandro"], "00s"),
    "Pink": ("pink", ["so-what", "who-knew", "get-the-party-started", "just-like-a-pill", "try", "just-give-me-a-reason", "raise-your-glass", "perfect"], "00s"),
    "Alicia Keys": ("alicia-keys", ["if-i-aint-got-you", "no-one", "fallin", "empire-state-of-mind", "girl-on-fire", "unthinkable", "you-dont-know-my-name"], "00s"),
    "Kelly Clarkson": ("kelly-clarkson", ["since-u-been-gone", "because-of-you", "breakaway", "stronger", "my-life-would-suck-without-you", "catch-my-breath", "behind-these-hazel-eyes"], "00s"),
    "Miley Cyrus": ("miley-cyrus", ["wrecking-ball", "party-in-the-usa", "we-cant-stop", "flowers", "midnight-sky", "the-climb", "malibu", "angels-like-you"], "10s"),
    "Selena Gomez": ("selena-gomez", ["lose-you-to-love-me", "good-for-you", "hands-to-myself", "same-old-love", "come-and-get-it", "the-heart-wants-what-it-wants", "wolves"], "10s"),
    "The Chainsmokers": ("the-chainsmokers", ["closer", "something-just-like-this", "dont-let-me-down", "paris", "roses", "all-we-know", "hope", "this-feeling"], "10s"),
    "Charlie Puth": ("charlie-puth", ["attention", "we-dont-talk-anymore", "one-call-away", "how-long", "done-for-me", "light-switch", "see-you-again"], "10s"),
    "Zedd": ("zedd", ["clarity", "the-middle", "stay", "spectrum", "find-you", "beautiful-now", "stay-the-night"], "10s"),
    "Calvin Harris": ("calvin-harris", ["feel-so-close", "summer", "this-is-what-you-came-for", "slide", "how-deep-is-your-love", "blame", "sweet-nothing"], "10s"),
    "Sia": ("sia", ["chandelier", "cheap-thrills", "elastic-heart", "titanium", "unstoppable", "alive", "the-greatest"], "10s"),
    "Doja Cat": ("doja-cat", ["say-so", "kiss-me-more", "woman", "paint-the-town-red", "need-to-know", "streets", "agora-hills"], "20s"),
    "Lil Nas X": ("lil-nas-x", ["industry-baby", "montero-call-me-by-your-name", "thats-what-i-want", "old-town-road", "panini", "holiday"], "20s"),
    "Sam Smith": ("sam-smith", ["stay-with-me", "im-not-the-only-one", "too-good-at-goodbyes", "dancing-with-a-stranger", "how-do-you-sleep", "unholy", "latch"], "10s"),
    "Sabrina Carpenter": ("sabrina-carpenter", ["espresso", "please-please-please", "nonsense", "feather", "because-i-liked-a-boy", "emails-i-cant-send", "tornado-warnings"], "20s"),
    "Lorde": ("lorde", ["royals", "ribs", "team", "green-light", "tennis-court", "perfect-places", "solar-power", "liability"], "10s"),
    "Frank Ocean": ("frank-ocean", ["thinkin-bout-you", "pink-white", "super-rich-kids", "nights", "novacane", "ivy", "self-control"], "10s"),
    "Paramore": ("paramore", ["misery-business", "that-s-what-you-get", "decode", "aint-it-fun", "still-into-you", "hard-times", "the-only-exception"], "00s"),
    "Avril Lavigne": ("avril-lavigne", ["complicated", "sk8er-boi", "girlfriend", "im-with-you", "my-happy-ending", "what-the-hell", "when-youre-gone"], "00s"),
    "My Chemical Romance": ("my-chemical-romance", ["welcome-to-the-black-parade", "teenagers", "im-not-okay", "helena", "famous-last-words", "na-na-na"], "00s"),
    "Fall Out Boy": ("fall-out-boy", ["sugar-were-goin-down", "dance-dance", "thnks-fr-th-mmrs", "centuries", "my-songs-know-what-you-did-in-the-dark", "immortals"], "00s"),
    "Gorillaz": ("gorillaz", ["feel-good-inc", "clint-eastwood", "dare", "on-melancholy-hill", "rhinestone-eyes", "dirty-harry"], "00s"),
    "Usher": ("usher", ["yeah", "burn", "u-got-it-bad", "my-boo", "dj-got-us-fallin-in-love", "omg", "confessions-part-ii"], "00s"),
    "TLC": ("tlc", ["waterfalls", "no-scrubs", "creep", "unpretty", "red-light-special", "diggin-on-you"], "90s"),
    "Boyz II Men": ("boyz-ii-men", ["ill-make-love-to-you", "end-of-the-road", "on-bended-knee", "water-runs-dry", "motownphilly", "a-song-for-mama"], "90s"),
    "Black Eyed Peas": ("black-eyed-peas", ["i-gotta-feeling", "boom-boom-pow", "where-is-the-love", "meet-me-halfway", "my-humps", "pump-it", "imma-be"], "00s"),
    "Kings of Leon": ("kings-of-leon", ["use-somebody", "sex-on-fire", "radioactive", "waste-a-moment", "revelry", "closer"], "00s"),
    "Hozier": ("hozier", ["take-me-to-church", "cherry-wine", "work-song", "almost-sweet-music", "movement", "shrike", "too-sweet"], "10s"),
    "John Legend": ("john-legend", ["ordinary-people", "all-of-me", "green-light", "save-room", "used-to-love-u", "love-me-now"], "00s"),
    "Nelly Furtado": ("nelly-furtado", ["maneater", "promiscuous", "say-it-right", "im-like-a-bird", "turn-off-the-light"], "00s"),
    "Norah Jones": ("norah-jones", ["dont-know-why", "come-away-with-me", "sunrise", "turn-me-on", "those-sweet-words"], "00s"),
    "Alanis Morissette": ("alanis-morissette", ["ironic", "you-oughta-know", "hand-in-my-pocket", "head-over-feet", "uninvited", "thank-u"], "90s"),
    "Weezer": ("weezer", ["buddy-holly", "undone-the-sweater-song", "say-it-aint-so", "island-in-the-sun", "beverly-hills", "hash-pipe", "pork-and-beans"], "90s"),
    "No Doubt": ("no-doubt", ["dont-speak", "just-a-girl", "spiderwebs", "hella-good", "underneath-it-all", "sunday-morning"], "90s"),
    "Foo Fighters": ("foo-fighters", ["everlong", "my-hero", "learn-to-fly", "monkey-wrench", "the-pretender", "best-of-you", "times-like-these"], "90s"),
    "U2": ("u2", ["one", "with-or-without-you", "beautiful-day", "i-still-havent-found-what-im-looking-for", "vertigo", "sunday-bloody-sunday", "where-the-streets-have-no-name"], "90s"),
    "R.E.M.": ("rem", ["everybody-hurts", "losing-my-religion", "the-one-i-love", "its-the-end-of-the-world-as-we-know-it", "man-on-the-moon"], "90s"),
    "Whitney Houston": ("whitney-houston", ["i-will-always-love-you", "i-have-nothing", "run-to-you", "greatest-love-of-all", "i-wanna-dance-with-somebody"], "90s"),
    "Celine Dion": ("celine-dion", ["my-heart-will-go-on", "the-power-of-love", "because-you-loved-me", "its-all-coming-back-to-me-now", "all-by-myself"], "90s"),
    "The Smashing Pumpkins": ("the-smashing-pumpkins", ["1979", "today", "bullet-with-butterfly-wings", "disarm", "tonight-tonight", "zero"], "90s"),
    "Backstreet Boys": ("backstreet-boys", ["i-want-it-that-way", "everybody", "as-long-as-you-love-me", "show-me-the-meaning-of-being-lonely", "larger-than-life", "shape-of-my-heart"], "90s"),
    "NSYNC": ("nsync", ["bye-bye-bye", "its-gonna-be-me", "tearin-up-my-heart", "this-i-promise-you", "pop", "girlfriend"], "90s"),
    "Blink-182": ("blink-182", ["all-the-small-things", "whats-my-age-again", "i-miss-you", "adam-s-song", "first-date", "feeling-this"], "90s"),
    "The Cranberries": ("the-cranberries", ["zombie", "linger", "dreams", "ode-to-my-family", "animal-instinct"], "90s"),
    "Aerosmith": ("aerosmith", ["i-dont-want-to-miss-a-thing", "cryin", "crazy", "dream-on", "sweet-emotion", "walk-this-way"], "90s"),
    "Goo Goo Dolls": ("goo-goo-dolls", ["iris", "slide", "name", "black-balloon", "here-is-gone"], "90s"),
    "Shania Twain": ("shania-twain", ["man-i-feel-like-a-woman", "youre-still-the-one", "that-dont-impress-me-much", "from-this-moment-on", "any-man-of-mine"], "90s"),
    "Glass Animals": ("glass-animals", ["heat-waves", "gooey", "youth", "life-itself", "the-other-side-of-paradise", "pork-soda"], "20s"),
    "Tate McRae": ("tate-mcrae", ["you-broke-me-first", "she-s-all-i-wanna-be", "greedy", "exes", "run-for-the-hills", "10-35"], "20s"),
    "Conan Gray": ("conan-gray", ["heather", "maniac", "memories", "people-watching", "telepath", "disaster"], "20s"),
    "Benson Boone": ("benson-boone", ["beautiful-things", "in-the-stars", "ghost-town", "slow-it-down"], "20s"),
    "Zach Bryan": ("zach-bryan", ["something-in-the-orange", "i-remember-everything", "heading-south", "burn-burn-burn", "sun-to-me", "tourniquet"], "20s"),
    "Chris Stapleton": ("chris-stapleton", ["tennessee-whiskey", "you-should-probably-leave", "starting-over", "broken-halos", "fire-away", "parachute"], "20s"),
    "PinkPantheress": ("pinkpantheress", ["just-for-me", "boys-a-liar", "pain", "break-it-off", "passion"], "20s"),
    "Steve Lacy": ("steve-lacy", ["bad-habit", "dark-red", "in-n-out", "static", "sunflower"], "20s"),
    "Rosalia": ("rosalia", ["malamente", "con-altura", "despecha", "bizcochito", "saoko", "la-fama"], "20s"),
    "Noah Kahan": ("noah-kahan", ["stick-season", "dial-drunk", "northern-attitude", "homesick", "everywhere-everything", "call-your-mom"], "20s"),
    "Laufey": ("laufey", ["bewitched", "from-the-start", "valentine", "falling-behind", "let-you-break-my-heart-again", "magnolia"], "20s"),
    "Renee Rapp": ("renee-rapp", ["too-well", "tummy-hurts", "snow-angel", "pretty-girls", "in-the-kitchen"], "20s"),
    "Tyla": ("tyla", ["water", "truth-or-dare", "art", "jump"], "20s"),
    "Victoria Monet": ("victoria-monet", ["on-my-mama", "moment", "jaguar", "touch-me"], "20s"),
    "Troye Sivan": ("troye-sivan", ["rush", "my-my-my", "youth", "wild", "fools", "one-of-your-girls"], "20s")
}

with open("massive_song_list.py", "w", encoding="utf-8") as f:
    f.write("ARTIST_SONGS = {\n")
    for artist, (slug, songs, decade) in DATA.items():
        song_tuples_str = ", ".join([f'("{slug}", "{s}", "{decade}")' for s in songs])
        f.write(f'    "{artist}": [{song_tuples_str}],\n')
    f.write("}\n")
