ARTIST_SONGS = {
    # =========================================================================
    # 90s (약 100+곡)
    # =========================================================================
    "Nirvana": [("nirvana", "smells-like-teen-spirit", "90s"), ("nirvana", "come-as-you-are", "90s"), ("nirvana", "lithium", "90s"), ("nirvana", "heart-shaped-box", "90s")],
    "Radiohead": [("radiohead", "creep", "90s"), ("radiohead", "fake-plastic-trees", "90s"), ("radiohead", "karma-police", "90s"), ("radiohead", "high-and-dry", "90s")],
    "Oasis": [("oasis", "wonderwall", "90s"), ("oasis", "dont-look-back-in-anger", "90s"), ("oasis", "champagne-supernova", "90s"), ("oasis", "live-forever", "90s")],
    "Green Day": [("green-day", "basket-case", "90s"), ("green-day", "when-i-come-around", "90s"), ("green-day", "good-riddance-time-of-your-life", "90s")],
    "Mariah Carey": [("mariah-carey", "always-be-my-baby", "90s"), ("mariah-carey", "hero", "90s"), ("mariah-carey", "fantasy", "90s"), ("mariah-carey", "vision-of-love", "90s")],
    "Pearl Jam": [("pearl-jam", "black", "90s"), ("pearl-jam", "even-flow", "90s"), ("pearl-jam", "alive", "90s"), ("pearl-jam", "jeremy", "90s")],
    "Red Hot Chili Peppers": [("red-hot-chili-peppers", "under-the-bridge", "90s"), ("red-hot-chili-peppers", "californication", "90s"), ("red-hot-chili-peppers", "scar-tissue", "90s"), ("red-hot-chili-peppers", "otherside", "90s")],
    "TLC": [("tlc", "waterfalls", "90s"), ("tlc", "no-scrubs", "90s"), ("tlc", "creep", "90s"), ("tlc", "unpretty", "90s")],
    "Boyz II Men": [("boyz-ii-men", "ill-make-love-to-you", "90s"), ("boyz-ii-men", "end-of-the-road", "90s"), ("boyz-ii-men", "on-bended-knee", "90s"), ("boyz-ii-men", "water-runs-dry", "90s")],
    "Madonna": [("madonna", "vogue", "90s"), ("madonna", "like-a-prayer", "90s"), ("madonna", "ray-of-light", "90s"), ("madonna", "frozen", "90s")],
    "Celine Dion": [("celine-dion", "my-heart-will-go-on", "90s"), ("celine-dion", "the-power-of-love", "90s"), ("celine-dion", "because-you-loved-me", "90s"), ("celine-dion", "its-all-coming-back-to-me-now", "90s")],
    "Whitney Houston": [("whitney-houston", "i-will-always-love-you", "90s"), ("whitney-houston", "i-have-nothing", "90s"), ("whitney-houston", "run-to-you", "90s")],
    "R.E.M.": [("rem", "everybody-hurts", "90s"), ("rem", "losing-my-religion", "90s"), ("rem", "the-one-i-love", "90s")],
    "U2": [("u2", "one", "90s"), ("u2", "with-or-without-you", "90s"), ("u2", "beautiful-day", "00s"), ("u2", "i-still-havent-found-what-im-looking-for", "90s")],
    "Foo Fighters": [("foo-fighters", "everlong", "90s"), ("foo-fighters", "my-hero", "90s"), ("foo-fighters", "learn-to-fly", "90s"), ("foo-fighters", "monkey-wrench", "90s")],
    "No Doubt": [("no-doubt", "dont-speak", "90s"), ("no-doubt", "just-a-girl", "90s"), ("no-doubt", "spiderwebs", "90s")],
    "Weezer": [("weezer", "buddy-holly", "90s"), ("weezer", "undone-the-sweater-song", "90s"), ("weezer", "say-it-aint-so", "90s"), ("weezer", "island-in-the-sun", "00s")],
    "Alanis Morissette": [("alanis-morissette", "ironic", "90s"), ("alanis-morissette", "you-oughta-know", "90s"), ("alanis-morissette", "hand-in-my-pocket", "90s"), ("alanis-morissette", "head-over-feet", "90s")],
    "Beck": [("beck", "where-its-at", "90s"), ("beck", "loser", "90s"), ("beck", "devils-haircut", "90s")],
    "The Smashing Pumpkins": [("the-smashing-pumpkins", "1979", "90s"), ("the-smashing-pumpkins", "today", "90s"), ("the-smashing-pumpkins", "bullet-with-butterfly-wings", "90s")],
    "Janet Jackson": [("janet-jackson", "together-again", "90s"), ("janet-jackson", "thats-the-way-love-goes", "90s")],
    "Spice Girls": [("spice-girls", "wannabe", "90s"), ("spice-girls", "2-become-1", "90s"), ("spice-girls", "say-youll-be-there", "90s")],
    "Backstreet Boys": [("backstreet-boys", "i-want-it-that-way", "90s"), ("backstreet-boys", "everybody", "90s"), ("backstreet-boys", "as-long-as-you-love-me", "90s")],
    "NSYNC": [("nsync", "bye-bye-bye", "00s"), ("nsync", "its-gonna-be-me", "00s"), ("nsync", "tearin-up-my-heart", "90s")],
    "Blink-182": [("blink-182", "all-the-small-things", "90s"), ("blink-182", "whats-my-age-again", "90s"), ("blink-182", "i-miss-you", "00s")],
    "The Cranberries": [("the-cranberries", "zombie", "90s"), ("the-cranberries", "linger", "90s"), ("the-cranberries", "dreams", "90s")],
    "Aerosmith": [("aerosmith", "i-dont-want-to-miss-a-thing", "90s"), ("aerosmith", "cryin", "90s"), ("aerosmith", "crazy", "90s")],
    "Shania Twain": [("shania-twain", "man-i-feel-like-a-woman", "90s"), ("shania-twain", "youre-still-the-one", "90s"), ("shania-twain", "that-dont-impress-me-much", "90s")],
    "Goo Goo Dolls": [("goo-goo-dolls", "iris", "90s"), ("goo-goo-dolls", "slide", "90s"), ("goo-goo-dolls", "name", "90s")],

    # =========================================================================
    # 00s (약 100+곡)
    # =========================================================================
    "Coldplay": [("coldplay", "the-scientist", "00s"), ("coldplay", "yellow", "00s"), ("coldplay", "viva-la-vida", "00s"), ("coldplay", "clocks", "00s")],
    "Linkin Park": [("linkin-park", "in-the-end", "00s"), ("linkin-park", "numb", "00s"), ("linkin-park", "what-ive-done", "00s"), ("linkin-park", "crawling", "00s")],
    "Maroon 5": [("maroon-5", "she-will-be-loved", "00s"), ("maroon-5", "sunday-morning", "00s"), ("maroon-5", "this-love", "00s"), ("maroon-5", "harder-to-breathe", "00s")],
    "Beyonce": [("beyonce", "crazy-in-love", "00s"), ("beyonce", "halo", "00s"), ("beyonce", "irreplaceable", "00s"), ("beyonce", "single-ladies", "00s")],
    "Norah Jones": [("norah-jones", "dont-know-why", "00s"), ("norah-jones", "come-away-with-me", "00s"), ("norah-jones", "sunrise", "00s")],
    "Nelly Furtado": [("nelly-furtado", "maneater", "00s"), ("nelly-furtado", "promiscuous", "00s"), ("nelly-furtado", "say-it-right", "00s")],
    "John Legend": [("john-legend", "ordinary-people", "00s"), ("john-legend", "all-of-me", "10s"), ("john-legend", "green-light", "00s")],
    "Rihanna": [("rihanna", "umbrella", "00s"), ("rihanna", "dont-stop-the-music", "00s"), ("rihanna", "take-a-bow", "00s"), ("rihanna", "disturbia", "00s")],
    "Britney Spears": [("britney-spears", "toxic", "00s"), ("britney-spears", "...baby-one-more-time", "90s"), ("britney-spears", "oops-i-did-it-again", "00s"), ("britney-spears", "womanizer", "00s")],
    "Justin Timberlake": [("justin-timberlake", "cry-me-a-river", "00s"), ("justin-timberlake", "what-goes-around-comes-around", "00s"), ("justin-timberlake", "rock-your-body", "00s")],
    "Usher": [("usher", "yeah", "00s"), ("usher", "burn", "00s"), ("usher", "u-got-it-bad", "00s"), ("usher", "my-boo", "00s")],
    "Gorillaz": [("gorillaz", "feel-good-inc", "00s"), ("gorillaz", "clint-eastwood", "00s"), ("gorillaz", "dare", "00s")],
    "The Killers": [("the-killers", "mr-brightside", "00s"), ("the-killers", "somebody-told-me", "00s"), ("the-killers", "when-you-were-young", "00s")],
    "The Strokes": [("the-strokes", "last-nite", "00s"), ("the-strokes", "reptilia", "00s"), ("the-strokes", "someday", "00s")],
    "Muse": [("muse", "supermassive-black-hole", "00s"), ("muse", "starlight", "00s"), ("muse", "uprising", "00s"), ("muse", "time-is-running-out", "00s")],
    "John Mayer": [("john-mayer", "gravity", "00s"), ("john-mayer", "your-body-is-a-wonderland", "00s"), ("john-mayer", "waiting-on-the-world-to-change", "00s"), ("john-mayer", "slow-dancing-in-a-burning-room", "00s")],
    "Alicia Keys": [("alicia-keys", "if-i-aint-got-you", "00s"), ("alicia-keys", "no-one", "00s"), ("alicia-keys", "fallin", "00s"), ("alicia-keys", "empire-state-of-mind", "00s")],
    "Pink": [("pink", "so-what", "00s"), ("pink", "who-knew", "00s"), ("pink", "get-the-party-started", "00s"), ("pink", "just-like-a-pill", "00s")],
    "Kelly Clarkson": [("kelly-clarkson", "since-u-been-gone", "00s"), ("kelly-clarkson", "because-of-you", "00s"), ("kelly-clarkson", "breakaway", "00s")],
    "Black Eyed Peas": [("black-eyed-peas", "i-gotta-feeling", "00s"), ("black-eyed-peas", "boom-boom-pow", "00s"), ("black-eyed-peas", "where-is-the-love", "00s")],
    "Fall Out Boy": [("fall-out-boy", "sugar-were-goin-down", "00s"), ("fall-out-boy", "dance-dance", "00s"), ("fall-out-boy", "thnks-fr-th-mmrs", "00s")],
    "My Chemical Romance": [("my-chemical-romance", "welcome-to-the-black-parade", "00s"), ("my-chemical-romance", "teenagers", "00s"), ("my-chemical-romance", "im-not-okay", "00s")],
    "Avril Lavigne": [("avril-lavigne", "complicated", "00s"), ("avril-lavigne", "sk8er-boi", "00s"), ("avril-lavigne", "girlfriend", "00s"), ("avril-lavigne", "im-with-you", "00s")],
    "Lady Gaga": [("lady-gaga", "bad-romance", "00s"), ("lady-gaga", "just-dance", "00s"), ("lady-gaga", "poker-face", "00s"), ("lady-gaga", "paparazzi", "00s")],
    "Taylor Swift": [("taylor-swift", "love-story", "00s"), ("taylor-swift", "you-belong-with-me", "00s"), ("taylor-swift", "teardrops-on-my-guitar", "00s"), ("taylor-swift", "our-song", "00s")],
    "Katy Perry": [("katy-perry", "i-kissed-a-girl", "00s"), ("katy-perry", "hot-n-cold", "00s"), ("katy-perry", "teenage-dream", "10s"), ("katy-perry", "firework", "10s")],
    "Jason Mraz": [("jason-mraz", "im-yours", "00s"), ("jason-mraz", "lucky", "00s")],
    "Paramore": [("paramore", "misery-business", "00s"), ("paramore", "that-s-what-you-get", "00s"), ("paramore", "decode", "00s")],
    "Kings of Leon": [("kings-of-leon", "use-somebody", "00s"), ("kings-of-leon", "sex-on-fire", "00s")],

    # =========================================================================
    # 10s (약 110+곡)
    # =========================================================================
    "Bruno Mars": [("bruno-mars", "just-the-way-you-are", "10s"), ("bruno-mars", "talking-to-the-moon", "10s"), ("bruno-mars", "grenade", "10s"), ("bruno-mars", "locked-out-of-heaven", "10s"), ("bruno-mars", "when-i-was-your-man", "10s")],
    "Adele": [("adele", "someone-like-you", "10s"), ("adele", "rolling-in-the-deep", "10s"), ("adele", "hello", "10s"), ("adele", "set-fire-to-the-rain", "10s")],
    "Ed Sheeran": [("ed-sheeran", "thinking-out-loud", "10s"), ("ed-sheeran", "perfect", "10s"), ("ed-sheeran", "shape-of-you", "10s"), ("ed-sheeran", "photograph", "10s")],
    "One Direction": [("one-direction", "what-makes-you-beautiful", "10s"), ("one-direction", "story-of-my-life", "10s"), ("one-direction", "drag-me-down", "10s"), ("one-direction", "night-changes", "10s")],
    "Hozier": [("hozier", "take-me-to-church", "10s"), ("hozier", "cherry-wine", "10s"), ("hozier", "work-song", "10s")],
    "Justin Bieber": [("justin-bieber", "love-yourself", "10s"), ("justin-bieber", "sorry", "10s"), ("justin-bieber", "what-do-you-mean", "10s"), ("justin-bieber", "baby", "10s")],
    "Ariana Grande": [("ariana-grande", "thank-u-next", "10s"), ("ariana-grande", "no-tears-left-to-cry", "10s"), ("ariana-grande", "into-you", "10s"), ("ariana-grande", "7-rings", "10s")],
    "The Weeknd": [("the-weeknd", "blinding-lights", "10s"), ("the-weeknd", "starboy", "10s"), ("the-weeknd", "the-hills", "10s"), ("the-weeknd", "cant-feel-my-face", "10s")],
    "Lord Huron": [("lord-huron", "the-night-we-met", "10s"), ("lord-huron", "ends-of-the-earth", "10s")],
    "Vance Joy": [("vance-joy", "riptide", "10s"), ("vance-joy", "mess-is-mine", "10s")],
    "Imagine Dragons": [("imagine-dragons", "radioactive", "10s"), ("imagine-dragons", "demons", "10s"), ("imagine-dragons", "believer", "10s"), ("imagine-dragons", "thunder", "10s")],
    "Twenty One Pilots": [("twenty-one-pilots", "stressed-out", "10s"), ("twenty-one-pilots", "ride", "10s"), ("twenty-one-pilots", "heathens", "10s")],
    "Halsey": [("halsey", "without-me", "10s"), ("halsey", "colors", "10s"), ("halsey", "bad-at-love", "10s")],
    "Billie Eilish": [("billie-eilish", "bad-guy", "10s"), ("billie-eilish", "ocean-eyes", "10s"), ("billie-eilish", "when-the-partys-over", "10s")],
    "Shawn Mendes": [("shawn-mendes", "stitches", "10s"), ("shawn-mendes", "treat-you-better", "10s"), ("shawn-mendes", "theres-nothing-holdin-me-back", "10s"), ("shawn-mendes", "in-my-blood", "10s")],
    "Dua Lipa": [("dua-lipa", "new-rules", "10s"), ("dua-lipa", "dont-start-now", "10s"), ("dua-lipa", "idgaf", "10s")],
    "Sam Smith": [("sam-smith", "stay-with-me", "10s"), ("sam-smith", "im-not-the-only-one", "10s"), ("sam-smith", "too-good-at-goodbyes", "10s")],
    "Frank Ocean": [("frank-ocean", "thinkin-bout-you", "10s"), ("frank-ocean", "pink-white", "10s"), ("frank-ocean", "super-rich-kids", "10s")],
    "Lana Del Rey": [("lana-del-rey", "summertime-sadness", "10s"), ("lana-del-rey", "young-and-beautiful", "10s"), ("lana-del-rey", "video-games", "10s"), ("lana-del-rey", "born-to-die", "10s")],
    "Lorde": [("lorde", "royals", "10s"), ("lorde", "ribs", "10s"), ("lorde", "team", "10s"), ("lorde", "green-light", "10s")],
    "Meghan Trainor": [("meghan-trainor", "all-about-that-bass", "10s"), ("meghan-trainor", "like-im-gonna-lose-you", "10s"), ("meghan-trainor", "dear-future-husband", "10s")],
    "The Chainsmokers": [("the-chainsmokers", "closer", "10s"), ("the-chainsmokers", "something-just-like-this", "10s"), ("the-chainsmokers", "dont-let-me-down", "10s"), ("the-chainsmokers", "paris", "10s")],
    "Post Malone": [("post-malone", "circles", "10s"), ("post-malone", "rockstar", "10s"), ("post-malone", "better-now", "10s"), ("post-malone", "sunflower", "10s")],
    "Charlie Puth": [("charlie-puth", "attention", "10s"), ("charlie-puth", "we-dont-talk-anymore", "10s"), ("charlie-puth", "one-call-away", "10s")],
    "Zedd": [("zedd", "clarity", "10s"), ("zedd", "the-middle", "10s"), ("zedd", "stay", "10s")],
    "Calvin Harris": [("calvin-harris", "feel-so-close", "10s"), ("calvin-harris", "summer", "10s"), ("calvin-harris", "this-is-what-you-came-for", "10s")],
    "Sia": [("sia", "chandelier", "10s"), ("sia", "cheap-thrills", "10s"), ("sia", "elastic-heart", "10s")],
    "Selena Gomez": [("selena-gomez", "lose-you-to-love-me", "10s"), ("selena-gomez", "good-for-you", "10s"), ("selena-gomez", "hands-to-myself", "10s")],
    "Miley Cyrus": [("miley-cyrus", "wrecking-ball", "10s"), ("miley-cyrus", "party-in-the-usa", "00s"), ("miley-cyrus", "we-cant-stop", "10s")],
    "Arctic Monkeys": [("arctic-monkeys", "do-i-wanna-know", "10s"), ("arctic-monkeys", "r-u-mine", "10s"), ("arctic-monkeys", "505", "00s"), ("arctic-monkeys", "fluorescent-adolescent", "00s")],

    # =========================================================================
    # 20s (약 110+곡)
    # =========================================================================
    "Olivia Rodrigo": [("olivia-rodrigo", "drivers-license", "20s"), ("olivia-rodrigo", "good-4-u", "20s"), ("olivia-rodrigo", "deja-vu", "20s"), ("olivia-rodrigo", "traitor", "20s"), ("olivia-rodrigo", "vampire", "20s")],
    "Sabrina Carpenter": [("sabrina-carpenter", "espresso", "20s"), ("sabrina-carpenter", "please-please-please", "20s"), ("sabrina-carpenter", "nonsense", "20s"), ("sabrina-carpenter", "feather", "20s")],
    "Harry Styles": [("harry-styles", "as-it-was", "20s"), ("harry-styles", "watermelon-sugar", "10s"), ("harry-styles", "falling", "10s"), ("harry-styles", "golden", "10s"), ("harry-styles", "late-night-talking", "20s")],
    "Glass Animals": [("glass-animals", "heat-waves", "20s"), ("glass-animals", "gooey", "10s"), ("glass-animals", "youth", "10s")],
    "Tate McRae": [("tate-mcrae", "you-broke-me-first", "20s"), ("tate-mcrae", "she-s-all-i-wanna-be", "20s"), ("tate-mcrae", "greedy", "20s")],
    "Conan Gray": [("conan-gray", "heather", "20s"), ("conan-gray", "maniac", "20s"), ("conan-gray", "memories", "20s")],
    "Benson Boone": [("benson-boone", "beautiful-things", "20s"), ("benson-boone", "in-the-stars", "20s")],
    "SZA": [("sza", "kill-bill", "20s"), ("sza", "good-days", "20s"), ("sza", "snooze", "20s"), ("sza", "the-weekend", "10s")],
    "Zach Bryan": [("zach-bryan", "something-in-the-orange", "20s"), ("zach-bryan", "i-remember-everything", "20s"), ("zach-bryan", "heading-south", "10s")],
    "Chris Stapleton": [("chris-stapleton", "tennessee-whiskey", "10s"), ("chris-stapleton", "you-should-probably-leave", "20s"), ("chris-stapleton", "starting-over", "20s")],
    "PinkPantheress": [("pinkpantheress", "just-for-me", "20s"), ("pinkpantheress", "boys-a-liar", "20s")],
    "Steve Lacy": [("steve-lacy", "bad-habit", "20s"), ("steve-lacy", "dark-red", "10s"), ("steve-lacy", "in-n-out", "20s")],
    "d4vd": [("d4vd", "romantic-homicide", "20s"), ("d4vd", "here-with-me", "20s")],
    "Rosalia": [("rosalia", "malamente", "10s"), ("rosalia", "con-altura", "10s"), ("rosalia", "despecha", "20s")],
    "Noah Kahan": [("noah-kahan", "stick-season", "20s"), ("noah-kahan", "dial-drunk", "20s"), ("noah-kahan", "northern-attitude", "20s")],
    "Chappell Roan": [("chappell-roan", "good-luck-babe", "20s"), ("chappell-roan", "pink-pony-club", "20s"), ("chappell-roan", "red-wine-supernova", "20s"), ("chappell-roan", "hot-to-go", "20s")],
    "Tyla": [("tyla", "water", "20s")],
    "Victoria Monet": [("victoria-monet", "on-my-mama", "20s")],
    "Renee Rapp": [("renee-rapp", "too-well", "20s"), ("renee-rapp", "tummy-hurts", "20s")],
    "Laufey": [("laufey", "bewitched", "20s"), ("laufey", "from-the-start", "20s"), ("laufey", "valentine", "20s")],
    "NewJeans": [("newjeans", "hype-boy", "20s"), ("newjeans", "super-shy", "20s"), ("newjeans", "ditto", "20s"), ("newjeans", "omg", "20s")],
    "Fifty Fifty": [("fifty-fifty", "cupid", "20s")],
    "The Weeknd (20s)": [("the-weeknd", "save-your-tears", "20s"), ("the-weeknd", "die-for-you", "10s"), ("the-weeknd", "out-of-time", "20s"), ("the-weeknd", "is-there-someone-else", "20s")],
    "Dua Lipa (20s)": [("dua-lipa", "levitating", "20s"), ("dua-lipa", "dance-the-night", "20s"), ("dua-lipa", "houdini", "20s"), ("dua-lipa", "physical", "20s")],
    "Doja Cat": [("doja-cat", "say-so", "20s"), ("doja-cat", "kiss-me-more", "20s"), ("doja-cat", "woman", "20s"), ("doja-cat", "paint-the-town-red", "20s")],
    "Lil Nas X": [("lil-nas-x", "industry-baby", "20s"), ("lil-nas-x", "montero-call-me-by-your-name", "20s"), ("lil-nas-x", "thats-what-i-want", "20s")],
    "Taylor Swift (20s)": [("taylor-swift", "anti-hero", "20s"), ("taylor-swift", "cruel-summer", "10s"), ("taylor-swift", "cardigan", "20s"), ("taylor-swift", "willow", "20s"), ("taylor-swift", "blank-space", "10s")],
    "Billie Eilish (20s)": [("billie-eilish", "happier-than-ever", "20s"), ("billie-eilish", "what-was-i-made-for", "20s"), ("billie-eilish", "everything-i-wanted", "10s")],
    "Ariana Grande (20s)": [("ariana-grande", "we-cant-be-friends", "20s"), ("ariana-grande", "positions", "20s"), ("ariana-grande", "yes-and", "20s")],
    "Miley Cyrus (20s)": [("miley-cyrus", "flowers", "20s"), ("miley-cyrus", "midnight-sky", "20s")],
    "Troye Sivan": [("troye-sivan", "rush", "20s"), ("troye-sivan", "my-my-my", "10s")],
}
