import json

NOTEBOOK_PATH = "chord_progression_analysis.ipynb"

with open(NOTEBOOK_PATH, 'r', encoding='utf-8') as f:
    nb = json.load(f)

# ── 셀 5: feat_brightness 추가 ──────────────────────────────────────────────
CELL5_SOURCE = [
    "# 3. 로마숫자 변환기 및 피처 추출 함수 정의\n",
    "\n",
    "def clean_chord_for_music21(chord_name):\n",
    "    c = str(chord_name).split('/')[0] # 베이스음 생략\n",
    "    c = c.replace('min', 'm').replace('maj', 'Maj')\n",
    "    return c\n",
    "\n",
    "def convert_to_roman_numeral(chord_name, key_str):\n",
    "    is_minor_key = key_str.endswith('m')\n",
    "    key_name = key_str[:-1].lower() if is_minor_key else key_str.upper()\n",
    "    try:\n",
    "        k_obj = key.Key(key_name) if not is_minor_key else key.Key(key_name, 'minor')\n",
    "        from music21 import harmony, roman, key\n",
    "        c_clean = clean_chord_for_music21(chord_name)\n",
    "        cs = harmony.ChordSymbol(c_clean)\n",
    "        rn = roman.romanNumeralFromChord(cs, k_obj)\n",
    "        return rn\n",
    "    except Exception:\n",
    "        return None\n",
    "\n",
    "def extract_base_features_and_sequence(row):\n",
    "    chords = str(row['raw_chords']).split()\n",
    "    key_str = row['key']\n",
    "    is_minor_key = key_str.endswith('m')\n",
    "\n",
    "    rn_objects = []\n",
    "    for c in chords:\n",
    "        rn = convert_to_roman_numeral(c, key_str)\n",
    "        if rn is not None:\n",
    "            rn_objects.append((c, rn))\n",
    "\n",
    "    if not rn_objects:\n",
    "        return pd.Series([0.0, 0.0, 0.0, 0.0, 0.0, []], \n",
    "                         index=['feat_unique_chords', 'feat_non_diatonic_ratio', \n",
    "                                'feat_minor_ratio', 'feat_tension_ratio', 'feat_brightness', 'rn_sequence'])\n",
    "\n",
    "    total_chords = len(rn_objects)\n",
    "    unique_chords = len(set([c[0] for c in rn_objects]))\n",
    "    feat_unique_chords = unique_chords / total_chords\n",
    "\n",
    "    major_diatonic = {'I', 'ii', 'iii', 'IV', 'V', 'vi', 'viio', 'vii°'}\n",
    "    minor_diatonic = {'i', 'iio', 'ii°', 'bIII', 'III', 'iv', 'v', 'V', 'bVI', 'VI', 'bVII', 'VII'}\n",
    "\n",
    "    non_diatonic_count = 0\n",
    "    minor_count = 0\n",
    "    tension_count = 0\n",
    "    major_diatonic_count = 0\n",
    "    rn_sequence = []\n",
    "\n",
    "    for c_name, rn in rn_objects:\n",
    "        fig = rn.figure\n",
    "        rn_sequence.append(fig)\n",
    "\n",
    "        if is_minor_key:\n",
    "            is_diatonic = any(fig.startswith(d) for d in minor_diatonic)\n",
    "        else:\n",
    "            is_diatonic = any(fig.startswith(d) for d in major_diatonic)\n",
    "            \n",
    "        if not is_diatonic:\n",
    "            non_diatonic_count += 1\n",
    "\n",
    "        is_minor_chord = rn.romanNumeralAlone.islower()\n",
    "        if is_minor_chord:\n",
    "            minor_count += 1\n",
    "            \n",
    "        # 밝기(Brightness)를 위한 메이저 다이아토닉 계산\n",
    "        is_diminished = 'o' in fig or '°' in fig\n",
    "        if is_diatonic and not is_minor_chord and not is_diminished:\n",
    "            major_diatonic_count += 1\n",
    "\n",
    "        c_lower = c_name.lower()\n",
    "        import re\n",
    "        tension_keywords = ['7', '9', '11', '13', 'add', '6']\n",
    "        has_tension = any(x in c_lower for x in tension_keywords)\n",
    "        if 'maj' in c_lower:\n",
    "            has_tension = has_tension or bool(re.search(r'maj\\d', c_lower))\n",
    "        if has_tension:\n",
    "            tension_count += 1\n",
    "\n",
    "    feat_non_diatonic_ratio = non_diatonic_count / total_chords\n",
    "    feat_minor_ratio        = minor_count / total_chords\n",
    "    feat_tension_ratio      = tension_count / total_chords\n",
    "    feat_brightness         = major_diatonic_count / total_chords\n",
    "\n",
    "    return pd.Series([feat_unique_chords, feat_non_diatonic_ratio,\n",
    "                      feat_minor_ratio, feat_tension_ratio, feat_brightness, rn_sequence],\n",
    "                     index=['feat_unique_chords', 'feat_non_diatonic_ratio',\n",
    "                            'feat_minor_ratio', 'feat_tension_ratio', 'feat_brightness', 'rn_sequence'])\n",
    "\n",
    "print(\"피처 추출 엔진 빌드가 완료되었습니다. 전처리를 시작합니다...\")\n",
    "df_base = df_songs.apply(extract_base_features_and_sequence, axis=1)\n",
    "df_processed = pd.concat([df_songs, df_base], axis=1)\n",
    "print(f\"✅ 보조 화성 피처 (명도 지수 포함) 추출 완료: {len(df_processed)}곡\")\n"
]

# ── 셀 6: 움직임 및 종지 피처 ────────────────────────────────────────────────
CELL6_SOURCE = [
    "# ── 코드 진행 움직임 및 특정 화성 어법(Cadence) 추출 ────────────────────────\n",
    "import re as _re\n",
    "\n",
    "ROMA_TO_DEGREE = {'I': 1, 'II': 2, 'III': 3, 'IV': 4, 'V': 5, 'VI': 6, 'VII': 7}\n",
    "\n",
    "def figure_to_degree(figure):\n",
    "    \"\"\"로마숫자 figure → 스케일 도수(1~7). 파싱 불가 시 None 반환.\"\"\"\n",
    "    fig = _re.sub(r'^[b#]+', '', str(figure))\n",
    "    m = _re.match(r'([IViv]+)', fig)\n",
    "    if not m:\n",
    "        return None\n",
    "    return ROMA_TO_DEGREE.get(m.group(1).upper())\n",
    "\n",
    "def extract_progression_features(degree_seq):\n",
    "    \"\"\"스케일 도수 시퀀스에서 코드 진행 움직임 및 화성 어법(종지) 피처 추출.\"\"\"\n",
    "    if len(degree_seq) < 2:\n",
    "        return {'feat_step_motion': 0.0, 'feat_leap_motion': 0.0,\n",
    "                'feat_cadence_perfect': 0.0, 'feat_cadence_plagal': 0.0, 'feat_cadence_deceptive': 0.0}\n",
    "                \n",
    "    total_transitions = len(degree_seq) - 1\n",
    "    step_count = 0\n",
    "    leap_count = 0\n",
    "    perfect_count = 0\n",
    "    plagal_count = 0\n",
    "    deceptive_count = 0\n",
    "    \n",
    "    for i in range(total_transitions):\n",
    "        prev = degree_seq[i]\n",
    "        curr = degree_seq[i+1]\n",
    "        \n",
    "        diff = curr - prev\n",
    "        while diff > 3:  diff -= 7\n",
    "        while diff < -3: diff += 7\n",
    "        abs_diff = abs(diff)\n",
    "        \n",
    "        # 움직임 특성\n",
    "        if abs_diff in [1, 2]: # 순차 진행 (2도, 3도 이동)\n",
    "            step_count += 1\n",
    "        elif abs_diff in [3, 4]: # 도약 진행 (4도, 5도 이동)\n",
    "            leap_count += 1\n",
    "            \n",
    "        # 화성 어법(종지) 특성\n",
    "        if prev == 5 and curr == 1:\n",
    "            perfect_count += 1\n",
    "        elif prev == 4 and curr == 1:\n",
    "            plagal_count += 1\n",
    "        elif prev == 5 and curr == 6:\n",
    "            deceptive_count += 1\n",
    "            \n",
    "    return {\n",
    "        'feat_step_motion': step_count / total_transitions,\n",
    "        'feat_leap_motion': leap_count / total_transitions,\n",
    "        'feat_cadence_perfect': perfect_count / total_transitions,\n",
    "        'feat_cadence_plagal': plagal_count / total_transitions,\n",
    "        'feat_cadence_deceptive': deceptive_count / total_transitions\n",
    "    }\n",
    "\n",
    "# ── 스케일 도수 시퀀스 변환 ─────────────────────────────────────────────────\n",
    "df_processed['degree_sequence'] = df_processed['rn_sequence'].apply(\n",
    "    lambda seq: [d for d in (figure_to_degree(f) for f in seq) if d is not None]\n",
    ")\n",
    "\n",
    "# ── 진행 움직임 및 종지 피처 추출 ──────────────────────────────────────────\n",
    "prog_feats = df_processed['degree_sequence'].apply(extract_progression_features)\n",
    "df_prog = pd.DataFrame(prog_feats.tolist())\n",
    "df_processed = pd.concat([df_processed, df_prog], axis=1)\n",
    "print(\"✅ 코드 진행 움직임(Step/Leap) 및 화성 어법(Cadence) 피처 추출 완료!\")\n"
]

# ── 셀 7: all_features 업데이트 ─────────────────────────────────────────────
CELL7_SOURCE = [
    "# 4. 화성 피처 스케일링\n",
    "all_features = [\n",
    "    # 1. 분위기 (Mood)\n",
    "    'feat_brightness', 'feat_minor_ratio', 'feat_tension_ratio',\n",
    "    # 2. 움직임 에너지 (Motion Energy)\n",
    "    'feat_step_motion', 'feat_leap_motion',\n",
    "    # 3. 화성 어법/종지 (Functional Cadence)\n",
    "    'feat_cadence_perfect', 'feat_cadence_plagal', 'feat_cadence_deceptive'\n",
    "]\n",
    "\n",
    "scaler = MinMaxScaler()\n",
    "df_scaled = df_processed.copy()\n",
    "df_scaled[all_features] = scaler.fit_transform(df_scaled[all_features])\n",
    "\n",
    "print(f\"✅ 피처 정규화(Min-Max Scaling) 완료\")\n",
    "print(f\"   적용된 총 피처 수: {len(all_features)}개\")\n"
]

# ── 셀 10: clustering_features 업데이트 ────────────────────────────────────
CELL10_SOURCE = [
    "# 아티스트 단위 피처 행렬 생성 (레이더 차트 + K-Means 공통 사용)\n",
    "clustering_features = [\n",
    "    'feat_brightness', 'feat_minor_ratio', 'feat_tension_ratio',\n",
    "    'feat_step_motion', 'feat_leap_motion',\n",
    "    'feat_cadence_perfect', 'feat_cadence_plagal', 'feat_cadence_deceptive'\n",
    "]\n",
    "\n",
    "df_cluster = df_scaled.copy()\n",
    "df_cluster['artist_base'] = df_cluster['artist'].apply(lambda x: x.split(' (')[0])\n",
    "artist_features = df_cluster.groupby('artist_base')[clustering_features].mean()\n",
    "print(f\"✅ 아티스트 단위 피처 행렬 생성 완료: {len(artist_features)}명\")\n"
]

nb['cells'][5]['source'] = CELL5_SOURCE
nb['cells'][6]['source'] = CELL6_SOURCE
nb['cells'][7]['source'] = CELL7_SOURCE
nb['cells'][10]['source'] = CELL10_SOURCE

# 이전에 추가했던 dominant_pattern 관련 시각화(셀 13, 14)도 임시로 비워두거나 단순하게 변경해야 함
# 사용자가 시각화가 맘에 안든다고 했으니, 여기선 시각화를 제외하고 마크다운만 간단히 정리
CELL13_SOURCE = [
    "### Phase 2. 화성 어법(Cadence) 및 움직임 프로파일링\n",
    "새롭게 추출한 피처들을 통해 각 아티스트가 어떤 종지(Cadence)를 선호하는지, 리드미컬한 도약(Leap)과 서정적인 순차(Step) 진행 중 무엇을 선호하는지 분석합니다.\n"
]
nb['cells'][13]['source'] = CELL13_SOURCE
nb['cells'][14]['source'] = ["# 시각화 코드 작성 예정 (사용자 피드백 후 진행)"]

with open(NOTEBOOK_PATH, 'w', encoding='utf-8') as f:
    json.dump(nb, f, ensure_ascii=False, indent=1)
